all: compilar executar

compilar:
	gcc -o kwic *.c

#adicionar comando -[aorcs]
#adicionar caminho do arquivo de entrada
#adicionar o int para o contexto 
#adicionar a query a ser buscada
executar:
	./kwic -r in/7668.txt 15 "better thing"
